server:
  port: ${SYS_ENV_SERVER_PORT}

spring:
  sql:
    init:
      mode:
  datasource:
    url: jdbc:postgresql://${SYS_ENV_POSTGRES_HOST}:${SYS_ENV_POSTGRES_PORT}/${SYS_ENV_POSTGRES_DATABASE}
    username: ${SYS_ENV_POSTGRES_USERNAME}
    password: ${SYS_ENV_POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db.changelog/changelog-cumulative.xml
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: auto

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
